apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: my-rabbit
  name: my-rabbit
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-rabbit
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: my-rabbit
    spec:
      containers:
      - image: rabbitmq:3-management
        name: rabbitmq
        resources: {}
status: {}
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: my-rabbit
  name: my-rabbit
spec:
  ports:
  - port: 5672
    protocol: TCP
    targetPort: 5672
    name: tcp-port
  - port: 15672
    protocol: TCP
    targetPort: 15672
    name: http
  selector:
    app: my-rabbit
status:
  loadBalancer: {}
